name: Build Unity Project

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('**/*.cs') }}
          restore-keys: |
            Library-

      - name: Activate Unity License
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: 2022.3.10f1
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Build project
        uses: game-ci/unity-builder@v3
        with:
          unityVersion: 2022.3.10f1
          targetPlatform: StandaloneLinux64
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build/StandaloneLinux64

      - name: Return Unity License
        if: always()
        uses: game-ci/unity-return-license@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
