name: Build Unity Project

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('**/*.cs') }}
          restore-keys: |
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v3
        with:
          unityVersion: 2022.3.10f1
          targetPlatform: StandaloneLinux64
